### ISSUE TITLE
No such file or directory: ../new_rigid_schema.json 

### ISSUE THREAD

**Issue by asamadi22** [zhanghaicang/carbonmatrix_public#1]
I am receiving an error of 'No such file or directory...' relating to the 'new_rigid_schema.json' file. I'm not sure if this is supposed to be included in the repo or if it's something that should be generated based on the PDB. The full error: 

```
Traceback (most recent call last):
  File "/Users/ayasamadi/Desktop/carbonmatrix_public/run_carbondesign.py", line 15, in <module>
    from carbondesign.data.pdbio import save_pdb
  File "/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/data/pdbio.py", line 14, in <module>
    from carbondesign.common import residue_constants
  File "/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/common/residue_constants.py", line 201, in <module>
    rigid_group_atom_positions = load_rigid_schema()
                                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/common/residue_constants.py", line 198, in load_rigid_schema
    with open(new_schema_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/common/new_rigid_schema.json'
```

**Comment by zhanghaicang** [comment]
Thanks for your comments. We have uploaded the missing files and updated README. If you have any other questions, please let us know.

**Comment by zhanghaicang** [comment]
> Thanks for your comments. We have uploaded the missing files and updated README. If you have any other questions, please let us know.



> I am receiving an error of 'No such file or directory...' relating to the 'new_rigid_schema.json' file. I'm not sure if this is supposed to be included in the repo or if it's something that should be generated based on the PDB. The full error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/ayasamadi/Desktop/carbonmatrix_public/run_carbondesign.py", line 15, in <module>
>     from carbondesign.data.pdbio import save_pdb
>   File "/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/data/pdbio.py", line 14, in <module>
>     from carbondesign.common import residue_constants
>   File "/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/common/residue_constants.py", line 201, in <module>
>     rigid_group_atom_positions = load_rigid_schema()
>                                  ^^^^^^^^^^^^^^^^^^^
>   File "/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/common/residue_constants.py", line 198, in load_rigid_schema
>     with open(new_schema_path) as f:
>          ^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/ayasamadi/Desktop/carbonmatrix_public/carbondesign/common/new_rigid_schema.json'
> ```

Thanks for your comments. We have uploaded the missing files and updated README. If you have any other questions, please let us know.
